#!/usr/bin/env bash

PWD=$(pwd)
git_hash=$(git rev-parse --short HEAD)

echo "Working dir: $PWD"

echo
echo "### Updating git hash"
ruby "$PWD/contrib/update_version.rb" "$git_hash"
echo
echo "#### Committing git hash update ####"
git add _config.yml
git commit -m "Updating version to $git_hash"
git push


echo "### Building site ###"
JEKYLL_ENV=production bundle exec jekyll build

echo "### Uploading to the server ###"
sshopts="-o StrictHostKeyChecking=no -i ~/.ssh/mario_rsa"
rsync --rsh="ssh $sshopts" -rP _site/ deploy@jrgnsn.net:/var/www/jrgnsn.net/ --delete