#!/usr/bin/env bash

PWD=$(pwd)
git_hash=$(git rev-parse --short HEAD)

echo "Working dir: $PWD"

echo
echo "### Updating git hash"
echo "$git_hash"
echo -ne "$git_hash" > "$PWD/_includes/version"
echo

echo "### Building site ###"
JEKYLL_ENV=production bundle exec jekyll build
echo

echo "### Uploading to the server ###"
sshopts="-o StrictHostKeyChecking=no -i ~/.ssh/mario_rsa"
rsync --rsh="ssh $sshopts" -rP _site/ deploy@jrgnsn.net:/var/www/jrgnsn.net/ --delete