image: debian/stable
packages:
  - curl
  - rsync
  - ruby
  - ruby-dev
  - zlib1g-dev
sources:
  - https://git.sr.ht/~mjorgensen/jrgnsn.net
environment:
  deploy: deploy@jrgnsn.net
secrets:
  - 7a042c0a-91f1-4e14-b2cb-5e1aaf23411e
triggers:
  - action: email
    condition: always
    to: notify@jrgnsn.net
tasks:
  - is-master: |
      cd jrgnsn.net
      if [ "$(git rev-parse master)" != "$(git rev-parse HEAD)" ]; then
        complete-build;
      fi
  - openring: |
      curl -O https://yukari.sr.ht/openring
      chmod +x openring
      cd jrgnsn.net
      ../openring \
        -s https://blacklivesmatter.com/rss \
        -s https://marco.org/rss.xml \
        -s https://drewdevault.com/feed.xml \
        -s https://www.caseyliss.com/rss \
        -s https://stardust.fm/posts/rss.xml \
        < _includes/webring_in.html \
        > _includes/webring_out.html
  - setup: |
      sudo gem install bundler github-pages -N
  - build: |
      cd jrgnsn.net
      bundle install
      JEKYLL_ENV=production bundle exec jekyll build
  - deploy: |
      cd jrgnsn.net
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP _site/ ${deploy}:/var/www/jrgnsn.net/ --delete
