image: debian/stretch
packages:
  - curl
  - rsync
  - ruby
  - ruby-dev
  - zlib1g-dev
sources:
  - https://git.sr.ht/~mjorgensen/jrgnsn.net
environment:
  deploy: deploy@jrgnsn.net
secrets:
  - 7a042c0a-91f1-4e14-b2cb-5e1aaf23411e
triggers:
  - action: email
    condition: always
    to: notify@jrgnsn.net
tasks:
  - openring: |
      curl -O https://yukari.sr.ht/openring
      chmod +x openring
      cd jrgnsn.net
      ../openring \
        -s https://drewdevault.com/feed.xml \
        -s https://www.jertype.com/feed.xml \
        < _includes/webring-in.html \
        > _includes/webring-out.html
  - setup: |
      sudo gem install bundler github-pages -N
  - build: |
      cd jrgnsn.net
      bundle install
      bundle exec jekyll build
  - deploy: |
      cd jrgnsn.net
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP _site/ ${deploy}:/var/www/jrgnsn.net/
