---
title: Matthew's Blog
description: Thoughts, stories, hacks, and ideas.
baseurl: ''
url: ''
markdown: kramdown
highlighter: rouge
lang: en
plugins:
- jekyll-paginate
- jekyll-seo-tag
- jekyll-target-blank
- nokogiri
paginate: 5
paginate_path: "/page/:num"
sass:
  style: compressed
target-blank:
  noreferrer: false
collections:
  projects:
    output: true
    permalink: "/projects/:name:output_ext"
  travel:
    output: true
    permalink: "/travel/:name:output_ext"
  recipes:
    output: true
    permalink: "/recipe/:name:output_ext"
