title: Matthew's Blog
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts, stories, hacks, and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# permalink: /:year/:month/:day/:title:output_ext
markdown: kramdown
# theme: minima
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: /page/:num
collections:
  projects:
    output: true
    permalink: /project/:name