---
title: Matthew's Blog
description: Thoughts, stories, hacks, and ideas.
baseurl: ''
url: ''
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-paginate
- jekyll-seo-tag
- nokogiri
paginate: 10
paginate_path: "/page/:num"
sass:
  style: compressed
collections:
  projects:
    output: true
    permalink: "/projects/:name:output_ext"
  travel:
    output: true
    permalink: "/travel/:name:output_ext"
  recipes:
    output: true
    permalink: "/recipe/:name:output_ext"
git_hash: ca10d46
